mode: train
seed: 42
dataset_name: QM9_Lendvay_min2_max6_th01
data_params:
  root: /blob/Dataset/QM9_Lendvay_min2_max6_th01
  label: dipole_moment
  fragmentor_kwargs:
    topoBO_threshold: 1.0
    min_kernel_atoms_num: 2
    min_bo_threshold: 0.4
    expand_fbo_threshold: 0.2
    max_kernel_atoms_num: 6
    overlap_level: groups
    empr_bo_method: SimpleExp
  he_type: explicit
  implicit_rc: null
  frac_list:
  - 110000
  - 10000
  batch_size: 128
  num_workers: 6
model_params:
  he_as_node_init: true
  use_he_degree_embedding: true
  use_he_as_message: false
  use_he_scalar: false
  update_he_feature: true
  irreps_out: 1x0e
  irreps_node_embedding: 128x0e+64x1o+32x2e
  irreps_hyperedge_embedding: 128x0e+64x1o+32x2e
  num_layers: 3
  irreps_sh: 1x0e+1x1o+1x2e
  max_radius: 6.0
  number_of_basis: 128
  rbf_basis_type: gaussian
  fc_neurons:
  - 64
  - 64
  irreps_node_feature: 512x0e
  irreps_hyperedge_feature: null
  irreps_head: 32x0e+16x1o+8x2e
  num_heads: 4
  irreps_pre_attn: null
  rescale_degree: false
  nonlinear_message: true
  irreps_mlp_mid: 384x0e+192x1o+96x2e
  use_attn_head: false
  norm_layer: layer
  alpha_drop: 0.2
  proj_drop: 0.0
  out_drop: 0.0
  drop_path_rate: 0.0
  mean_out: false
  scale: null
  atomref: null
  output_force: false
train_params:
  ddp: false
  accelerator: gpu
  num_devices: 1
  opt: adamw
  opt_eps: 1.0e-08
  opt_betas: null
  clip_grad: null
  momentum: 0.9
  weight_decay: 0.005
  sched: cosine
  lr: 0.0005
  lr_noise: null
  lr_noise_pct: 0.67
  lr_noise_std: 1.0
  warmup_lr: 1.0e-06
  min_lr: 1.0e-06
  decay_epochs: 30
  warmup_epochs: 5
  cooldown_epochs: 10
  patience_epochs: 10
  decay_rate: 0.1
  epochs: 400
  max_time: 00:300:00:00
  standardize: true
  criterion: mae
  save_path: /blob/Models/QM9_Lendvay_min2_max6_th01/2024-01-27-15-11-05_AblationExp-mprr3_dipole_moment_batch128_heasnode_heasattr_FalseScalar_hedeg-embed_updatehe_3layer_rc6.0_32G1-V100
  load_ckpt: null
